# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Analyzer(object):
    def setupUi(self, Analyzer):
        Analyzer.setObjectName("Analyzer")
        Analyzer.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Analyzer.sizePolicy().hasHeightForWidth())
        Analyzer.setSizePolicy(sizePolicy)
        Analyzer.setMinimumSize(QtCore.QSize(1000, 600))
        Analyzer.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(Analyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.display_origin = QtWidgets.QTextEdit(self.centralwidget)
        self.display_origin.setGeometry(QtCore.QRect(0, 0, 460, 555))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_origin.sizePolicy().hasHeightForWidth())
        self.display_origin.setSizePolicy(sizePolicy)
        self.display_origin.setMinimumSize(QtCore.QSize(410, 555))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.display_origin.setFont(font)
        self.display_origin.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.display_origin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.display_origin.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.display_origin.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.display_origin.setReadOnly(True)
        self.display_origin.setObjectName("display_origin")
        self.comboBox_date = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_date.setGeometry(QtCore.QRect(460, 0, 80, 22))
        self.comboBox_date.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_date.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_date.setObjectName("comboBox_date")
        self.display_select = QtWidgets.QTextEdit(self.centralwidget)
        self.display_select.setGeometry(QtCore.QRect(540, 0, 460, 555))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_select.sizePolicy().hasHeightForWidth())
        self.display_select.setSizePolicy(sizePolicy)
        self.display_select.setMinimumSize(QtCore.QSize(0, 555))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.display_select.setFont(font)
        self.display_select.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.display_select.setToolTipDuration(-1)
        self.display_select.setMidLineWidth(0)
        self.display_select.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.display_select.setReadOnly(True)
        self.display_select.setObjectName("display_select")
        self.comboBox_time = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_time.setGeometry(QtCore.QRect(460, 30, 80, 22))
        self.comboBox_time.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_time.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_time.setObjectName("comboBox_time")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(460, 60, 80, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setAutoDefault(False)
        self.pushButton_search.setFlat(False)
        self.pushButton_search.setObjectName("pushButton_search")
        Analyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Analyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        Analyzer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Analyzer)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Analyzer.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(Analyzer)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(Analyzer)
        self.action_save.setObjectName("action_save")
        self.menu_F.addAction(self.action_open)
        self.menu_F.addAction(self.action_save)
        self.menubar.addAction(self.menu_F.menuAction())

        self.retranslateUi(Analyzer)
        QtCore.QMetaObject.connectSlotsByName(Analyzer)

    def retranslateUi(self, Analyzer):
        _translate = QtCore.QCoreApplication.translate
        Analyzer.setWindowTitle(_translate("Analyzer", "MainWindow"))
        self.pushButton_search.setText(_translate("Analyzer", "搜索"))
        self.pushButton_search.setShortcut(_translate("Analyzer", "Return"))
        self.menu_F.setTitle(_translate("Analyzer", "文件(F)"))
        self.action_open.setText(_translate("Analyzer", "打开(O)"))
        self.action_open.setIconText(_translate("Analyzer", "打开(O)"))
        self.action_open.setShortcut(_translate("Analyzer", "Ctrl+O"))
        self.action_save.setText(_translate("Analyzer", "保存(S)"))
        self.action_save.setShortcut(_translate("Analyzer", "Ctrl+S"))

