# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Analyzer(object):
    def setupUi(self, Analyzer):
        Analyzer.setObjectName("Analyzer")
        Analyzer.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Analyzer.sizePolicy().hasHeightForWidth())
        Analyzer.setSizePolicy(sizePolicy)
        Analyzer.setMinimumSize(QtCore.QSize(1000, 600))
        Analyzer.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(Analyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.display_select = QtWidgets.QTextEdit(self.centralwidget)
        self.display_select.setGeometry(QtCore.QRect(470, 0, 460, 555))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_select.sizePolicy().hasHeightForWidth())
        self.display_select.setSizePolicy(sizePolicy)
        self.display_select.setMinimumSize(QtCore.QSize(0, 555))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.display_select.setFont(font)
        self.display_select.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.display_select.setToolTipDuration(-1)
        self.display_select.setMidLineWidth(0)
        self.display_select.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.display_select.setReadOnly(True)
        self.display_select.setObjectName("display_select")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 101, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBox_time2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_time2.setGeometry(QtCore.QRect(10, 160, 80, 22))
        self.comboBox_time2.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_time2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_time2.setObjectName("comboBox_time2")
        self.pushButton_search = QtWidgets.QPushButton(self.frame)
        self.pushButton_search.setGeometry(QtCore.QRect(10, 190, 80, 23))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setAutoDefault(False)
        self.pushButton_search.setFlat(False)
        self.pushButton_search.setObjectName("pushButton_search")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 54, 12))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox_date2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_date2.setGeometry(QtCore.QRect(10, 130, 80, 22))
        self.comboBox_date2.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_date2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_date2.setObjectName("comboBox_date2")
        self.pushButton_save = QtWidgets.QPushButton(self.frame)
        self.pushButton_save.setGeometry(QtCore.QRect(50, 440, 41, 23))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setFlat(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_note = QtWidgets.QPushButton(self.frame)
        self.pushButton_note.setGeometry(QtCore.QRect(10, 440, 41, 23))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_note.setFont(font)
        self.pushButton_note.setAutoDefault(False)
        self.pushButton_note.setFlat(False)
        self.pushButton_note.setObjectName("pushButton_note")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 101, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(101, 101))
        self.frame_2.setMaximumSize(QtCore.QSize(101, 101))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(5)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.frame_3.setStyleSheet("background-color: rgb(61, 96, 248);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.comboBox_date1 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_date1.setGeometry(QtCore.QRect(10, 5, 80, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_date1.sizePolicy().hasHeightForWidth())
        self.comboBox_date1.setSizePolicy(sizePolicy)
        self.comboBox_date1.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_date1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_date1.setStyleSheet("")
        self.comboBox_date1.setObjectName("comboBox_date1")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(0, 31, 101, 31))
        self.frame_5.setStyleSheet("background-color: rgb(247, 100, 92);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.comboBox_time1 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_time1.setGeometry(QtCore.QRect(10, 5, 80, 22))
        self.comboBox_time1.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_time1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_time1.setObjectName("comboBox_time1")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(0, 60, 101, 41))
        self.frame_6.setStyleSheet("background-color: rgb(33, 36, 53);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(0, 20, 54, 12))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Analyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Analyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        Analyzer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Analyzer)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Analyzer.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(Analyzer)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(Analyzer)
        self.action_save.setObjectName("action_save")
        self.menu_F.addAction(self.action_open)
        self.menu_F.addAction(self.action_save)
        self.menubar.addAction(self.menu_F.menuAction())

        self.retranslateUi(Analyzer)
        QtCore.QMetaObject.connectSlotsByName(Analyzer)

    def retranslateUi(self, Analyzer):
        _translate = QtCore.QCoreApplication.translate
        Analyzer.setWindowTitle(_translate("Analyzer", "MainWindow"))
        self.pushButton_search.setText(_translate("Analyzer", "搜索"))
        self.pushButton_search.setShortcut(_translate("Analyzer", "Return"))
        self.label_2.setText(_translate("Analyzer", "结束"))
        self.pushButton_save.setText(_translate("Analyzer", "保存"))
        self.pushButton_save.setShortcut(_translate("Analyzer", "Return"))
        self.pushButton_note.setText(_translate("Analyzer", "笔记"))
        self.pushButton_note.setShortcut(_translate("Analyzer", "Return"))
        self.label.setText(_translate("Analyzer", "开始"))
        self.menu_F.setTitle(_translate("Analyzer", "文件(F)"))
        self.action_open.setText(_translate("Analyzer", "打开(O)"))
        self.action_open.setIconText(_translate("Analyzer", "打开(O)"))
        self.action_open.setShortcut(_translate("Analyzer", "Ctrl+O"))
        self.action_save.setText(_translate("Analyzer", "保存(S)"))
        self.action_save.setShortcut(_translate("Analyzer", "Ctrl+S"))

